### ISSUE TITLE
We need a proper name

### ISSUE THREAD

**Issue by dylanatsmith** [email-markup-consortium/email-markup-consortium#4]
Note: We may find it easier to agree a name after the mission statement is resolved (https://github.com/email-standards/email-standards/issues/3).

## Initial ideas

* Email Standards Community Group
* HELOWG
  + @hteumeuleu: "This is one along the vibe of WHATWG (Web Hypertext Application Technology Working Group). HELO is command for SMTP servers. We could try to find a fun acronym for it. (Like HTML Emails L… O… Can't think of something for now.)"
* HTML Email Standards Project
* HTML Email Living Standard Community Group
* HTML Email Code Standards Project
* Email Rendering Standards Community Group
* HTML Email Community Group
* HTML Standards for Email Community Group

## Group vs. Project

@M-J-Robbins:
> Currently I'm thinking group or community group. If this grows we could have the wide  community group making suggestions and a smaller working group putting things into action. Also a number of projects can live inside the group.

@dylanatsmith:
> "Project" kind of implies a fixed timeframe to me.

@hteumeuleu:
> Same. I'm not sure why but I feel like "Working Group" or "Community Group" has a more official vibe and is more common among standards group (W3C, IETF).

## The case for "Community Group"

[Interesting distinction between different types of W3C groups](https://github.com/w3c/wg-effectiveness/blob/master/process.md#w3c-interest-and-working-groups):

> There are two types of W3C group:
>
> Working Groups: work on deliverables, usually Technical Reports (standards).
> Interest Groups: evaluate potential Web technologies and policies. Do not work on Technical Reports.

@dylanatsmith:
> Reading through mission statements on [those](https://www.w3.org/groups/ig/) [pages](https://github.com/w3cping/) as well as the working groups list, it looks like:
>
> - Interest groups’ missions tend to mention things like best practices, awareness, engagement, exploring solutions, hosting discussions, participation, etc.
> - Working groups’ missions tend to mention writing specs other other tangible outputs.
>
> I think “Community Group” gives us the flexibility to operate in either domain?

@husseinalhammad:
> I think individually Interest and Working groups' focus could be too narrow for us right now. The term "Community Group" is nice and gives me the impression we're open and approachable.

## Other considerations

* Open UI doesn't use any specifier. They're just "Open UI." Is there a similarly short name that would be descriptive enough for us?
* We are aware of the seemingly defunct [HTML for Email Community Group](https://www.w3.org/community/htmail/); our name should be distinct from theirs

**Comment by Malvoz** [comment]
> Open UI doesn't use any specifier. They're just "Open UI."

While they do refer to themselves as only "Open UI" on their Github repo and website, they are registered as "Open UI Community Group" with the W3C: https://www.w3.org/community/open-ui/

**Comment by dylanatsmith** [comment]
> I think any name that has "HTML" in it gives the impression that the standards are only concerned with HTML, but not CSS, SVG, ARIA, HTTP headers, etc. (as applicable).

This is a good point. I think "HTML Email" was an attempt at addressing @davecrocker's feedback on the mission statement drafting (see https://github.com/email-standards/email-standards/issues/3) that "email" is much bigger than just the email object.

I also like "Email Standards" and "Email Standards Community Group" but is it too broad for what we have in mind? Maybe it is, but it's okay because our mission will clarify?

**Comment by husseinalhammad** [comment]
Perhaps "Email Standards" is too broad and would overlaps with out-of-scope areas such as protocols. It seems the term "Email Standards" is more commonly used to describe the standards required for mail servers and email clients to support like SMTP and POP3. There's also a book titled [Essential Email Standards: RFCs and Protocols Made Practical](https://www.amazon.com/Essential-Email-Standards-Protocols-Practical/dp/0471345970).

If using "HTML" seems to limiting, could we perhaps use the term "web" somehow instead?

**Comment by hteumeuleu** [comment]
I think "Email Standards" itself is way too broad, and could make our intentions confusing with other groups like BIMIgroup.com. HTML emails is a common industry term to denote what we want to work on, and I think the inclusion of CSS, ARIA, etc. is implicit.

**Comment by dylanatsmith** [comment]
Would "Email Rendering Standards" suitably clarify without specifying a single language?

**Comment by hteumeuleu** [comment]
I believe "Rendering" is a specific technical term that reflects how to interpret code and visually interpret them, which I don't think is our goal at all. Our work is more towards "Filtering" or "Embedding" than rendering.

**Comment by davecrocker** [comment]
Interesting thread.  And yes, navigating naming tradeoffs is a hassle.  (First startup I was involved in had a venture guy who did a wonderful job mentoring us for a long time, about everything.  Until we got to the issue of choosing name.  He refused to touch that, since he said it was alwasy divisive.)

Trying to avoid confusing with existing work, such as protocol standards is a good idea, of course.  So is trying to avoid misunderstanding.  I think your intended scope is far broader than the mechanics of rendering, since you really are concerned with having a data object moving around that gets consistent treatment.  Rendering isn't irrelevant, but it's only related, IMO.  Another source of possible confusion is social and political content control.  (People are inventive when misinterpreting terms.)

The suggestion to focus first on the mission statement and then worry about the name is quite a good idea, I think.  It is often useful to have people explain what they are doing or what they want to produce, but using strictly non-technical language.  That is, formulate a statement that is understandable to an average, non-technical person. This often produces a statement that a) is easy to understand, b) has real substance, and c) gets everyone to share a common goal.  THEN they can go argue details...
/d

**Comment by alicemeichi** [comment]
**EMAILS Community Group**... with EMAILS being an acronym for:  Email Markup Applied Internet Living Standard? (Can be workshopped!)

At Squarespace (and at my previous company Shutterstock, actually) we differentiate between programmatic code like JS vs. _markup_ code like HTML and CSS. 

Considering that email development is mainly concerned with HTML and CSS, I feel that using "Markup" would more clearly delineate the exact development standards we're looking to achieve as well as distinguish ourselves from matters of email **_delivery_** like IMAP, SMTP and POP3.

**Comment by dylanatsmith** [comment]
I'm iffy on acronyms/backronyms in general but I think EMAILS is especially risky since it's liable to be unrecognised as an acronym and/or stylised as "Emails Community Group" which is even more vague than "Email Standards." There's a high risk for lack of clarity with this one.

Another problem could be specifying a "living standard" — we're trying to separate name and mission from possible projects, outputs, deliverables, etc. of which a living standard could be just one.

I do _really_ like the "Markup" suggestion though. That's a brilliant suggestion for solving the problem of "Email" not being specific enough and "HTML Email" not being broad enough.

If we mix that into some of the earlier ideas...

* Email Markup Standards Group
* Email Markup Community Group
* Email Markup Standards Community Group

Any of those names is immediately understandable without having to know what anything stands for, which is important. Readers would get a good picture straight away. A domain like `emailmarkupstandards.org` is strong, too.

**Comment by Malvoz** [comment]
> "Markup"

"Markup" focuses on the authoring aspect, while the mission statement includes users: "Guidelines for those who create, deliver, and receive email [...]", is that disconnect acceptable? "Email Authoring Standards Community Group" could be an alternative in that case.

What are your thoughts on "Web Standards for Email Community Group" (WECG)? The acronym is similar to the Web Platform Incubator CG (WICG): https://www.w3.org/community/wicg/ which "provides a lightweight venue for proposing and discussing new web platform features", where WECG instead "provides a venue for web standards in email"~.

**Comment by alicemeichi** [comment]
> "Markup" focuses on the authoring aspect, while the mission statement includes users: "Guidelines for those who create, deliver, and receive email [...]", is that disconnect acceptable? "Email Authoring Standards Community Group" could be an alternative in that case.

I suppose I would want to dig into the context behind exactly what those guidelines for users (vs. authors) might be? What do guidelines around how to "receive email" look like? Or should we consider removing that part if it's out of scope?

**Comment by davecrocker** [comment]
I'm also like the word 'markup' for the core focus of this group, given what I've seen you all in fact focus on, namely the HTML-related bits of content. So it is both accurate and precise.

I am /not/ fan of having the word 'standard' in almost any effort, since it refers to a relatively small bit of formal status, compared against what is usually a much larger context of usability and/or interoperability. It's better to focus on the substance than the process.

On the average, I come up with terrible acronyms, but this doesn't prevent me from sometimes suggestion them.  And today's indulgence is...

     More Usable Markup in Email
     
As a description of the substance, I think that is your goal, from what I've been seeing.  There is also a small attempt at humor, since the acronym is MUME, which is a riff on MIME...  So this would be The MUME Project.

Smacking of less cleverness might be the Email Markup Interoperability Project.  (EMIP isn't all that nifty either, though.) Or perhaps Project for Email Markup Interoperability (PEMI).

I'll stop now.  /d

**Comment by husseinalhammad** [comment]
> "Markup" focuses on the authoring aspect, while the mission statement includes

As the discussion is now circling back to the mission statement, perhaps we need to first focus on refining it (see: #3 [Mission statement](https://github.com/email-standards/email-standards/issues/3)) like @dylanatsmith suggested!

**Comment by dylanatsmith** [comment]
> "Markup" focuses on the authoring aspect

Part of the reason I like Alice's "markup" suggestion is because it feels to me like it doesn't centre entirely on the authoring experience.

Authoring the markup is a big problem today so we shouldn't ignore that, but that markup is then transformed by ESPs and again by email clients. The code that is written is never the code that is sent is never the code that is read.

We'll need all three parties involved to be successful and I think all three parties will have an interest in standardising the markup and what's done to it.

**Comment by M-J-Robbins** [comment]
Reading back over this I few words are standing out to me as having support from most of us 
_"Email", "Markup", "Community Group"_

So that leads me to the idea of 
**Email Markup Community Group (EMCG)**
(which @dylanatsmith mentioned before)

I also quite like the idea of adding a little more description 
**Email Markup Interoperability Community Group (EMICG)**
(similar to what @davecrocker mentioned before)

I like _"Interoperability"_  as it covers a lot of the things we've talked about.  This [definition of interoperability from W3](https://www.w3.org/People/Bos/DesignGuide/interoperability.html) is good. In fact [the whole document is interesting](https://www.w3.org/People/Bos/DesignGuide/toc.html) (I've not read it all, just quickly scanned over it)

Also **EMICG** isn't really used anywhere else I've seen.

**Comment by M-J-Robbins** [comment]
As discussed in the [last meeting](https://github.com/email-standards/email-standards/blob/main/meeting-notes/2021-09-14.md#3-finalising-name-mission-statement-etc) it's time to start wrapping up this issue and deciding on a name.

So firstly let's give everyone a week to get in a last minute suggestions,  deadline is Wednesday 22nd September.
From there we can make a shortlist and put it to a vote. Again the vote should be left open for a week to allow people to take part

So to get it started my suggestion for the shortlist is 

### Email Markup Interoperability Community Group (EMICG)
Pros:
* I think it's quite descriptive
* It's not too specific so should cover a range of the work we've discussed
*   "EMICG" isn't used much elsewhere so avoids any confusion and should be easy to get domain names

Cons:
* I would prefer an acronym like "EMIC" as it's nicer to say rather than an initialism "E.M.I.C.G" but I feel community group is a better fit so I'd want to keep the "G"

**Comment by megbosh** [comment]
Is the word "interoperability" too jargon-y? I kind of raised an eyebrow when I saw it, because I had never heard it before. Would "Compatibility" work better? We talked a lot about DEI and Accessibility in the last meeting and part of accessibility is not using jargon.

There's going to be a lot of educate folks on here, and I don't think the name should be one of them.

**Comment by hteumeuleu** [comment]
Can we name it **Responsive Email Markup Interoperability Community Group** please? This way I'd have managed to slip my first name in it :D Just kidding, I think EMICG is great and I say go for it.

**Comment by husseinalhammad** [comment]
> I would prefer an acronym like "EMIC" as it's nicer to say rather than an initialism "E.M.I.C.G" but I feel community group is a better fit so I'd want to keep the "G"

An option without the "G" could be Email Markup Interoperability Consortium. The "C" in W3C also stands for consortium. I think I like "community group" more.

---

> Is the word "interoperability" too jargon-y? I kind of raised an eyebrow when I saw it, because I had never heard it before. Would "Compatibility" work better? We talked a lot about DEI and Accessibility in the last meeting and part of accessibility is not using jargon.

That's a good point. We can certainly add "Email Markup Compatibility Community Group" to the shortlist.

The term "interoperability" doesn't seem to be uncommon in the wider tech industry though and in some contexts there seems to be a distinction between "interoperability" and "compatibility". 

Although the term is new to me personally, it didn't bother me because coming across new concepts/terms and looking them up is a regular occurence to anyone in this industry and our audience is a technical one. At the same time I think if we're going to use "interoperability", it may be worth adding it to the glossary of terms (#7).

**Comment by M-J-Robbins** [comment]
I really like that @husseinalhammad do you want to put that on the shortlist? Consortium seems to make a lot of sense.

Also wondering if the word [Emic](https://en.wikipedia.org/wiki/Emic_and_etic) maybe adds some additional meaning to it in some way? Or more likely I'm overthinking things again

**Comment by husseinalhammad** [comment]
Since we [started the shortlist](https://github.com/email-standards/email-standards/issues/4#issuecomment-919965983), I think this is what we have so far:

| Acronym | Name                                          |
| ------- | --------------------------------------------- |
| EMICG   | Email Markup Interoperability Community Group |
| EMIC    | Email Markup Interoperability Consortium      |
| EMCCG   | Email Markup Compatibility Community Group    |
| EMCC    | Email Markup Compatibility Consortium         |


The differences:

- "Interoperability" vs "Compatibility"
- "Community Group" vs "Consortium"

---

> Also wondering if the word Emic maybe adds some additional meaning to it in some way? Or more likely I'm overthinking things again

Clever!

**Comment by davecrocker** [comment]
On 9/18/2021 12:56 AM, Hussein Al Hammad wrote:
> Also wondering if the word Emic maybe adds some additional meaning to 
> it in some way? Or more likely I'm overthinking things again

As long as it isn't too silly or obnoxious, I think that being 
pronounceable is a win.  Not that the absence has hurt html or http all 
that much...

d/

-- 
Dave Crocker
***@***.***
408.329.0791

Volunteer, Silicon Valley Chapter
Information & Planning Coordinator
American Red Cross
***@***.***

**Comment by husseinalhammad** [comment]
Second round of voting has started:

- Where: Slack
- Deadline: Friday 1 October

**Comment by dylanatsmith** [comment]
We are now **Email Markup Consortium**. The GitHub org and repo names have been changed.
