### ISSUE TITLE
Group email code review

### ISSUE THREAD

**Issue by JayOram** [email-markup-consortium/email-markup-consortium#70]
## Project title
Group email code review

## Project description
The idea would be to create a design that has the fundamental elements found in a large number of emails. 

Headlines, full width images, 2 column layouts, Paragraphs of text, text links, call to actions, navigation menus etc. 

I would create a master design Figma file with open access, along with a starting point for the code. Creating 2x versions, one using Ghost tables and the other all tables. 

Then within Github ask contributors to create pull requests to update the HTML line by line with any amends that would create cleaner, accessible, well supported elements. With a team of reviewers agreeing the updates that would improve the code. 

## Why is this needed
This could benefit EMC by bringing together anyone who codes emails and allow them to improve on all the elements included, this could then inform the 'email best practice' project that the team are putting together.

Also providing a starting template for the wider email community to start an email file from - with up to date fixes, most accessible and most widely supported.

## Scope
This project will cover individual elements of an email. A heading, a block of text, a 2 column layout, an image - the building blocks to create an email. 

This is not a complete email or design for anyone to use, a framework or best practice guide. 

## Contributing members
Jay Oram (ActionRocket) + reviewers: hopefully other email coders would like to be involved.

## Where will the project be worked on, and where will the finished project be hosted?
EMC Github would be the best location - I'm unsure whether the discussion section or code repo would be best?

**Comment by M-J-Robbins** [comment]
This sounds interesting and I'd be up for contributing to it too. 

I think a new repo under the EMC GitHub org makes sense. Discussions can initially happen in GitHub discussions or on group calls. Then once the first version is out, discussion of improvements could be in github issues or PR's

**Comment by JayOram** [comment]
@alicemeichi - It would be easier to maintain one. But as we currently have these two branches of email development, I think it is important to show both examples. 

I'll make it clear that any change will be reflected in both files and any reasons why something wouldn't work will be shared in the discussion.

**Comment by husseinalhammad** [comment]
We like the idea and the goal, but feel email code is very nuanced which will make it very hard to give clear simple answers. Due to the amount of possible solutions to issues this may end up being more opinion based. So we’re not going to proceed for the moment.

To be more transparent: even us admins don't fully agree on email development approaches (due to preference and/or technical reasons). However, we do all agree on the qualities the end product should have. It is a lot easier to agree on the qualities of the end product vs the steps to achieve those qualities. And this is fine. There doesn't need to be a single solution. 

At the same time, given that it is not straightforward to get started with HTML email, we see how this can be helpful. So it is likely we will consider green lighting this at a later stage. 

I'll be closing this issue for now.

**Comment by alicemeichi** [comment]
Adding to this an example that even though the W3C exists, there's no single W3C-sponsored web framework even though there's the W3C standard. Similarly, the EMC shouldn't be too prescriptive of any particular Email framework even though we're pushing for fully-supported industry standards.
